#!/bin/bash
yum clean all

yum -y install yq jq curl gcc make perl libc-dev perl-dev unzip \
    && curl -L https://cpanmin.us | perl - --no-wget App::cpanminus

yum -y remove awscli
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install --update

yum -y install git

yum install docker -y
systemctl enable docker
service docker start
usermod -a -G docker ec2-user

echo "end userdata"